# .pre-commit-config.yaml
# Simple pre-commit configuration for trimming whitespace

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
